/**
 * @author Paul Rossouw
 * @date 23 Sep 2023
 * @details
 * \b This \b program \b needs: \n
 *   - The mesh (surface or volume) of the squid for current calculation \n
 *   - The settings.json generated by inductex \n \n
 * \b The \b process: \n
 *   1) Run inductEx to generate the neeeded mesh and settings files. \n
 *   2) Extract needed surface mesh using gmshEx.h. \n
 *   3) Take the output field file (eg B_field.vtk) and optimize the mesh using remesh.h. \n
 *   4) Run tth. \n
 *   5) Repeat 3 - 4. \n
 *   6) Use noiseEx.h to calculate the msfn
 */


#include <iostream>
#include "depend/noiseEx.h"

using namespace std;

int main(int argc, char **argv){

    // for testing the algorithm without mesh quality:
    string fileLoc = argv[1];
    double curr = stod(argv[2]);
    noiseEx n(fileLoc);


    cout << n.getMSFN(curr) << endl;

    cout << n.getArea() << endl;
//    n.debugDraw();
//    cout << n.getArea();

    return EXIT_SUCCESS;
}
