name: Build on multiple platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: download deps
      run: | 
        git clone https://github.com/pauldross/VTKParser.git
    - name: Set up CMake
      run: |
        mkdir build
        cd build
        cmake ..
      working-directory: ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config Release
      working-directory: ${{ github.workspace }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact-${{ runner.os }}
        path: ${{ github.workspace }}/build

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact-Linux
          path: ${{ github.workspace }}/build

      - name: Set up GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/build/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}  # Specify a tag for the release
          name: "Release ${{ github.run_number }}"
          body: "Release created by GitHub Actions."

      - name: Get Release URL
        run: | 
          echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"

